services:
  backend:
    build: ./backend
    restart: always
    env_file: .env
    volumes:
      - uploads_data:/app/uploads

  nginx:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  uploads_data:
